---

- name: Import Elastic PGP Public Key
  ansible.builtin.rpm_key:
    fingerprint: 4609 5ACC 8548 582C 1A26 99A9 D27D 666C D88E 42B4
    key: https://artifacts.elastic.co/GPG-KEY-elasticsearch

- name: Define Elasticsearch RPM Repository
  ansible.builtin.template:
    dest: /etc/yum.repos.d/elasticsearch.repo
    mode: '644'
    src: templates/repository/rpm/elasticsearch.repo.j2

- name: Download Elasticsearch RPM Package
  ansible.builtin.dnf:
    name: elasticsearch
    state: present
    enablerepo: elasticsearch
  notify:
    - 'Reload Systemd Daemon'
