---

- name: Add Elastic DEB822 Formatted Repository
  ansible.builtin.deb822_repository:
    signed_by: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    enabled: true
    name: elasticsearch
    components: main
    suites: stable
    uris: https://artifacts.elastic.co/packages/9.x/apt 

- name: Download Transport for HTTPS and Elasticsearch DEB Packages
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - elasticsearch={{ elasticsearch_major_version }}.{{ elasticsearch_minor_version }}
    update_cache: true
  notify:
    - 'Reload Systemd Daemon'
