---

- name: Get Service Facts
  ansible.builtin.service_facts:

- name: Disable Elasticsearch Unit
  ansible.builtin.systemd_service:
    enabled: false
    state: stopped
    name: elasticsearch.service
  when: "'elasticsearch.service' in ansible_facts.services"
  notify:
    - 'Reload Systemd Daemon'

- name: Remove APT Transport for HTTPS and Elasticsearch Packages
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - elasticsearch
    state: absent

- name: Delete Elastic APT Repository
  ansible.builtin.apt_repository:
    repo: 'deb [signed-by=/usr/share/keyrings/elasticsearch-keyring.asc] https://artifacts.elastic.co/packages/9.x/apt stable main'
    state: absent

- name: Delete Elastic PGP Public Key
  ansible.builtin.file:
    path: /usr/share/keyrings/elasticsearch-keyring.asc
    state: absent
